import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './globals.css'
import Link from 'next/link'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, headerBg = ' #edfcfc' }) {
  return (
    <html lang="fa">
      <body>
     <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        {children}
      </body>
    </html>
  )
}
